import type { Topic } from "../../types";
import { bestPracticesTopic } from "./factory";

export const bestPracticeCurriculumTopics: Topic[] = [
bestPracticesTopic({
  slug: "bp-quality",
  title: "Code quality",
  order: 1,
  summary: "Readability, coupling, cohesion, and what you defend in review.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Quality is how cheaply the next engineer (including you) can change the code correctly: clear names, small modules, low coupling, tests at the seams, and a review bar that catches design not just style.",
  beats: ["Readable > clever.", "Coupling is the interview word: who must change together?", "Review for invariants, not commas."],
  intro: "Interviewers listen for judgment, not Prettier settings.",
  why: "Most production bugs are communication failures in the codebase.",
  concept: "Cohesion: a module has one reason to change. Coupling: a change ripples.",
  how: "Extract when a name clarifies. Delete when an abstraction lies.",
  usage: "PR description, shared UI kit, domain functions.",
  practices: "Boy scout rule in the file you touch. Measure complexity before rewriting.",
  mistakes: "Drive-by refactors in a feature PR. Abstracting after one use.",
  language: "typescript",
  caption: "Code quality",
  code: "function canSubmit(order: Order) {\n  return order.items.length > 0 && order.totalCents > 0;\n}\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-quality.svg",
      alt: "Code quality",
      caption: "Code quality",
    },
  ],
  examples: [
    {
      id: "smell",
      title: "Flag coupling",
      about: "UI importing a database client.",
      language: "typescript",
      code: "// UI → domain → data. Not UI → sql.\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-structure",
  title: "Feature folders and boundaries",
  order: 2,
  summary: "Colocate by feature; publish a small public API per module.",
  prerequisites: [],
  related: ["bp-quality"],
  isHighYield: true,
  oneLiner: "Structure by feature (cart, billing) rather than by type (components/, hooks/) once the app is non-trivial. Each feature exposes a narrow public API; internals stay private. Cross-feature imports go through that API.",
  beats: ["Feature > layer for product apps.", "Public barrel vs deep imports.", "Boundaries beat folder aesthetics."],
  intro: "Architecture-lite that interviewers want on a whiteboard.",
  why: "Prevents the 'everyone imports everything' ball of mud.",
  concept: "A folder is a module if it has a public index and hidden internals.",
  how: "Move files when a feature is clear; don't start with 12 empty layers.",
  usage: "App Router colocation, design system package.",
  practices: "Depend inward on domain types. Ban circular features.",
  mistakes: "Shared/ dumping ground. Circular barrels.",
  language: "typescript",
  caption: "Feature folders and boundaries",
  code: "export { CartButton } from \"./cart-button\";\nexport type { CartItem } from \"./types\";\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-structure.svg",
      alt: "Feature folders and boundaries",
      caption: "Feature folders and boundaries",
    },
  ],
  examples: [
    {
      id: "ban",
      title: "Lint boundary",
      about: "eslint-plugin-import or nx tags.",
      language: "typescript",
      code: "// feature-a must not import feature-b/internal\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-reviews",
  title: "Code review habits",
  order: 3,
  summary: "What a useful review comments on.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "A good review asks: is this the right design, is it safe (authz, data), is it observable, and can we roll it back? Style is automated. Block on correctness and missing tests at risk points, not on taste.",
  beats: ["Automate format.", "Block on authz and data loss.", "Ask questions before demands."],
  intro: "Seniors are hired for review quality.",
  why: "Reviews are the team's design conversation.",
  concept: "Risk-based depth: auth and money get more eyes.",
  how: "Checklist: threat, failure, test, rollout.",
  usage: "PR templates, CODEOWNERS for payments.",
  practices: "Small PRs. Screenshots for UI. Feature flags for risky ones.",
  mistakes: "Drive-by nits as blocking. Reviewing after merge.",
  language: "typescript",
  caption: "Code review habits",
  code: "const REVIEW = [\"authz\", \"migrations\", \"observability\", \"rollback\"];\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-reviews.svg",
      alt: "Code review habits",
      caption: "Code review habits",
    },
  ],
  examples: [
    {
      id: "flag",
      title: "Risk label",
      about: "Label PRs that touch auth.",
      language: "typescript",
      code: "// CODEOWNERS: /src/auth @security\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-a11y",
  title: "Accessibility as default",
  order: 4,
  summary: "Keyboard, names, and semantics are product requirements.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Accessibility is not a polish phase: semantic HTML, keyboard paths, visible focus, names that match the UI, and contrast. If the design is mouse-only, the implementation is incomplete. Test with keyboard and a screen reader on the critical path.",
  beats: ["Name, role, value.", "Focus order follows visual order.", "Don't disable zoom."],
  intro: "Frontend interviews include a11y because law and users do.",
  why: "Inaccessible UI is a defect, not a nice-to-have.",
  concept: "Prefer native elements. ARIA is a last resort.",
  how: "Use the platform: button, a, label, dialog.",
  usage: "Forms, modals, tables, custom widgets.",
  practices: "Lint (eslint-plugin-jsx-a11y) plus manual keyboard pass.",
  mistakes: "div onClick as a button. Icon-only without a name.",
  language: "html",
  caption: "Accessibility as default",
  code: "<button type=\"button\" aria-expanded={open} onClick={toggle}>\n  Account\n</button>\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-a11y.svg",
      alt: "Accessibility as default",
      caption: "Accessibility as default",
    },
  ],
  examples: [
    {
      id: "label",
      title: "Visible label",
      about: "Placeholder is not a label.",
      language: "typescript",
      code: "<label htmlFor=\"email\">Email</label>\n<input id=\"email\" type=\"email\" />\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-contracts",
  title: "API contracts",
  order: 5,
  summary: "Types and runtime validation at the boundary.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "The network is not typed. Zod (or similar) at the edge of the app turns unknown JSON into a domain type or a failure. Share the schema with OpenAPI/tRPC if you can, but always validate on the client of an untrusted payload.",
  beats: ["Unknown at the boundary.", "Fail loudly on contract drift.", "Version APIs; don't silently reshape."],
  intro: "Frontend owns parsing even when backend 'has types'.",
  why: "Half the Heisenbugs are shape changes.",
  concept: "Parse, don't validate ad hoc ifs.",
  how: "schema.parse(await res.json()).",
  usage: "BFF, public APIs, localStorage.",
  practices: "Keep schemas next to the client. Generate when possible.",
  mistakes: "as User after fetch. Optional chaining as a contract.",
  language: "typescript",
  caption: "API contracts",
  code: "const User = z.object({ id: z.string(), email: z.string().email() });\nexport function parseUser(data: unknown) {\n  return User.parse(data);\n}\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-contracts.svg",
      alt: "API contracts",
      caption: "API contracts",
    },
  ],
  examples: [
    {
      id: "err",
      title: "Surface parse errors",
      about: "Don't swallow Zod issues.",
      language: "typescript",
      code: "try {\n  return User.parse(json);\n} catch (e) {\n  report(e);\n  throw e;\n}\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-testing-strategy",
  title: "Testing strategy",
  order: 6,
  summary: "What to unit, integrate, and skip.",
  prerequisites: [],
  related: ["test-pyramid"],
  isHighYield: true,
  oneLiner: "Test behavior at the cheapest reliable layer: pure domain in unit tests, user-visible flows in component tests, a few E2E journeys. Don't duplicate the same assertion at every layer. Skip tests that only lock CSS class names.",
  beats: ["Trophy/pyramid: more unit than E2E.", "Test what the user/domain cares about.", "Flakes destroy trust—delete or fix."],
  intro: "Strategy is a best practice; mechanics live in the Testing track.",
  why: "A suite nobody trusts is worse than a small suite.",
  concept: "Risk × cost. Auth and checkout get E2E.",
  how: "Write the test that would have caught the last Sev-1.",
  usage: "Design reviews, RFCs.",
  practices: "Contract tests for APIs you don't own.",
  mistakes: "100% coverage as a goal. Snapshot of the whole page.",
  language: "typescript",
  caption: "Testing strategy",
  code: "const layers = [\"unit\", \"component\", \"e2e\"] as const;\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-testing.svg",
      alt: "Testing strategy",
      caption: "Testing strategy",
    },
  ],
  examples: [
    {
      id: "skip",
      title: "What not to test",
      about: "Third-party internals.",
      language: "typescript",
      code: "// Don't test React's useState implementation\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-observability",
  title: "Frontend observability",
  order: 7,
  summary: "Logs, metrics, and user-facing error reports.",
  prerequisites: [],
  related: ["eh-logging"],
  isHighYield: false,
  oneLiner: "If it can fail in production, you need a signal: structured logs for server, client error reporting with release + user (carefully), and a metric for the journey (checkout started/finished). Console.log is not observability.",
  beats: ["Correlate session to server traces.", "Sample, don't drown.", "PII never in breadcrumbs."],
  intro: "Seniors debug with data, not SSH folklore.",
  why: "You cannot fix what you cannot see.",
  concept: "OpenTelemetry / vendor SDK + source maps.",
  how: "Wrap mutations; capture failed fetches with URL (no tokens).",
  usage: "RUM, error trackers, server logs.",
  practices: "Release health. Alert on error-rate spikes, not each error.",
  mistakes: "Logging access tokens. Alerting on 1-off network blips.",
  language: "typescript",
  caption: "Frontend observability",
  code: "reportError({ name: \"checkout_fail\", orderId, reason });\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-observability.svg",
      alt: "Frontend observability",
      caption: "Frontend observability",
    },
  ],
  examples: [
    {
      id: "srcmap",
      title: "Source maps",
      about: "Upload for production, hide from public if needed.",
      language: "typescript",
      code: "// CI: upload maps with the release hash\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-flags",
  title: "Feature flags",
  order: 8,
  summary: "Decouple deploy from release; keep flags short-lived.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Flags let you ship dark, test in prod, and kill a feature. Treat flag evaluation as a dependency: default fail-closed for risky features. Delete flags after rollout or you ship a second configuration language.",
  beats: ["Ship ≠ release.", "Flag in one place.", "Expiry date on every flag."],
  intro: "Interview classic for 'how do you roll out safely'.",
  why: "Reduces blast radius.",
  concept: "Boolean or multivariate; server-evaluated for security.",
  how: "SDK in a provider; don't scatter if (user.id === ...).",
  usage: "Kill switches, experiments.",
  practices: "Server-side flags for authz. Clean up.",
  mistakes: "Permanent flags. Client-only flags for paywall bypass.",
  language: "typescript",
  caption: "Feature flags",
  code: "if (flags.checkoutV2) return <CheckoutV2 />;\nreturn <CheckoutV1 />;\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-flags.svg",
      alt: "Feature flags",
      caption: "Feature flags",
    },
  ],
  examples: [
    {
      id: "kill",
      title: "Kill switch",
      about: "Ops can disable without deploy.",
      language: "typescript",
      code: "if (!flags.paymentsEnabled) return <PaymentsDown />;\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-complexity",
  title: "Complexity and YAGNI",
  order: 9,
  summary: "Essential vs accidental complexity.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Essential complexity is the domain; accidental is our abstractions. YAGNI: don't build the platform for one screen. Prefer deletion and boring code until a second use appears.",
  beats: ["Second use justifies abstraction.", "State is complexity.", "A diagram you cannot explain is a smell."],
  intro: "Expert-level interviews probe over-engineering.",
  why: "Time-to-change is the metric.",
  concept: "Count states, effect, and network calls.",
  how: "Inline first. Extract on pain.",
  usage: "Greenfield features.",
  practices: "Time-box spikes. Write the simpler alternative in the PR.",
  mistakes: "Generic framework for one form. Event buses for a checkbox.",
  language: "typescript",
  caption: "Complexity and YAGNI",
  code: "function price(cents: number) {\n  return (cents / 100).toFixed(2);\n}\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-complexity.svg",
      alt: "Complexity and YAGNI",
      caption: "Complexity and YAGNI",
    },
  ],
  examples: [
    {
      id: "state",
      title: "Count states",
      about: "Each boolean doubles UI paths.",
      language: "typescript",
      code: "// 4 booleans → 16 states. Collapse them.\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-dx",
  title: "Developer experience",
  order: 10,
  summary: "Fast feedback loops and boring defaults.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "DX is CI time, typecheck, local seed data, and scripts that match production. If onboarding takes a week of folklore, you will ship bugs. Invest in the loop you run a hundred times a day.",
  beats: ["Seconds matter in the inner loop.", "Prod-like data locally.", "Docs next to the command."],
  intro: "Leads are judged on team throughput.",
  why: "Slow loops cause skipped tests.",
  concept: "Hot reload, typed env, one-command bootstrap.",
  how: "Measure pnpm test and tsc in CI.",
  usage: "Monorepos, generators.",
  practices: "Fail CI on type errors. Keep fixtures small.",
  mistakes: "Custom webpack folklore nobody can upgrade.",
  language: "json",
  caption: "Developer experience",
  code: "\"scripts\": { \"dev\": \"next dev\", \"typecheck\": \"tsc --noEmit\" }\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-dx.svg",
      alt: "Developer experience",
      caption: "Developer experience",
    },
  ],
  examples: [
    {
      id: "seed",
      title: "Seed script",
      about: "Known users for QA.",
      language: "typescript",
      code: "pnpm db:seed\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-docs",
  title: "Documentation that ages",
  order: 11,
  summary: "Decision records and runnable examples.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Docs that survive are: why we chose X (ADRs), how to run it (README), and examples that compile. Comment why, not what. Delete docs when the code dies.",
  beats: ["ADR for irreversible choices.", "README: 5-minute start.", "Comments for invariants."],
  intro: "Seniors leave a paper trail.",
  why: "Tribal knowledge does not scale.",
  concept: "Docs as code, reviewed in the same PR.",
  how: "Short ADR: context, decision, consequences.",
  usage: "Architecture, runbooks.",
  practices: "Link to dashboards from runbooks.",
  mistakes: "Wikis that contradict the repo. Commented-out code as docs.",
  language: "typescript",
  caption: "Documentation that ages",
  code: "/** Charging twice is forbidden. Dedupe by idempotencyKey. */\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-docs.svg",
      alt: "Documentation that ages",
      caption: "Documentation that ages",
    },
  ],
  examples: [
    {
      id: "adr",
      title: "ADR stub",
      about: "One file per decision.",
      language: "typescript",
      code: "# ADR-12: Session cookies over localStorage tokens\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-enhancement",
  title: "Progressive enhancement",
  order: 12,
  summary: "HTML first; JS as upgrade.",
  prerequisites: [],
  related: ["next-server-actions"],
  isHighYield: false,
  oneLiner: "Critical flows should work with HTML + HTTP when possible (forms, links). JS upgrades UX. In Next, Server Actions on <form> are the modern version of this idea. Don't trap content behind a white screen of client JS.",
  beats: ["Links and forms work.", "JS is an enhancement.", "SSR/RSC help the first paint."],
  intro: "Resilience interview question.",
  why: "Bad networks and broken bundles happen.",
  concept: "Server-rendered HTML is the baseline.",
  how: "Use native form actions; hydrate for polish.",
  usage: "Checkout, search, auth.",
  practices: "Test with JS disabled on marketing pages at least.",
  mistakes: "SPA-only checkout with no SSR. Click handlers on <a> that preventDefault always.",
  language: "typescript",
  caption: "Progressive enhancement",
  code: "<form action={placeOrder}>\n  <button>Pay</button>\n</form>\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-enhancement.svg",
      alt: "Progressive enhancement",
      caption: "Progressive enhancement",
    },
  ],
  examples: [
    {
      id: "link",
      title: "Real links",
      about: "Shareable URLs.",
      language: "typescript",
      code: "<Link href={`/p/${id}`}>View</Link>\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-consistency",
  title: "UI consistency",
  order: 13,
  summary: "Tokens, patterns, and one way to do buttons.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Consistency is a design system: color/space/type tokens, a finite set of components, and forbidding one-off hex values. Inconsistent UI is a defect in a team product.",
  beats: ["Tokens over raw values.", "One Button API.", "Exceptions documented."],
  intro: "Frontend craft interview.",
  why: "Users notice mismatch more than missing features.",
  concept: "Theme on CSS variables; components consume tokens.",
  how: "Lint no hex in feature code if you have tokens.",
  usage: "Design systems, dark mode.",
  practices: "Compose; don't fork Button for every screen.",
  mistakes: "Copy-pasting 12 paddings. A second modal implementation.",
  language: "css",
  caption: "UI consistency",
  code: "button { background: var(--color-primary); }\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-consistency.svg",
      alt: "UI consistency",
      caption: "UI consistency",
    },
  ],
  examples: [
    {
      id: "token",
      title: "Token",
      about: "Name by role not hue.",
      language: "typescript",
      code: "--color-danger: #b00020;\n",
    }
  ],
}),

bestPracticesTopic({
  slug: "bp-hygiene",
  title: "Security hygiene",
  order: 14,
  summary: "Defaults that prevent the easy misses.",
  prerequisites: [],
  related: ["sec-xss", "sec-cookies"],
  isHighYield: false,
  oneLiner: "Hygiene is the everyday bar: no secrets in the client, encode output, allowlist URLs, dependency updates, and cookies with Secure/HttpOnly/SameSite. Deep attacks live in the Security track; this is the checklist you actually run.",
  beats: ["Secrets on the server.", "Encode, don't regex-sanitize HTML.", "Updates and lockfiles."],
  intro: "Best-practice interviews still poke XSS and tokens.",
  why: "Most incidents are missed defaults.",
  concept: "Safe defaults in templates and cookies.",
  how: "PR checklist + automated scanners.",
  usage: "Onboarding, templates.",
  practices: "Dependabot/Snyk plus human review of install scripts.",
  mistakes: "dangerouslySetInnerHTML for user content. Tokens in localStorage as the default.",
  language: "typescript",
  caption: "Security hygiene",
  code: "const html = escape(user.name);\n",
  figures: [
    {
      src: "/diagrams/best-practices/bp-hygiene.svg",
      alt: "Security hygiene",
      caption: "Security hygiene",
    },
  ],
  examples: [
    {
      id: "cookie",
      title: "Cookie flags",
      about: "Session cookie baseline.",
      language: "typescript",
      code: "Set-Cookie: session=…; HttpOnly; Secure; SameSite=Lax\n",
    }
  ],
}),
];
