import type { Topic } from "../../types";
import { errorHandlingTopic } from "./factory";

export const errorHandlingCurriculumTopics: Topic[] = [
errorHandlingTopic({
  slug: "eh-philosophy",
  title: "Failure as a product surface",
  order: 1,
  summary: "Errors are UX, telemetry, and control flow.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Error handling is not try/catch sprinkles. Decide: what does the user see, what is retried, what is logged, and what is fatal. Distinguish validation errors (user can fix), transient (retry), and bugs (report). Silent catch is a defect.",
  beats: ["User-visible vs operational.", "Don't swallow.", "Map errors to HTTP/UI states."],
  intro: "The thesis of this track.",
  why: "Trust dies on a spinner that never resolves.",
  concept: "Error taxonomy: 4xx, 5xx, timeout, offline, invariant.",
  how: "One mapper from domain errors to UI.",
  usage: "Any app.",
  practices: "Document the taxonomy in the design system (toast vs inline vs full page).",
  mistakes: "catch (e) {} empty. Alert(e) for everything.",
  language: "typescript",
  caption: "Failure as a product surface",
  code: "type AppError =\n  | { type: \"validation\"; fields: Record<string, string> }\n  | { type: \"unavailable\" }\n  | { type: \"bug\"; id: string };\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-philosophy.svg",
      alt: "Failure as a product surface",
      caption: "Failure as a product surface",
    },
  ],
  examples: [
    {
      id: "map",
      title: "Map",
      about: "Never show raw stacks to users.",
      language: "typescript",
      code: "function toUi(e: AppError) {\n  if (e.type === \"unavailable\") return \"Try again shortly\";\n  return \"Something went wrong\";\n}\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-boundaries",
  title: "Error boundaries",
  order: 2,
  summary: "React: catch render errors in the subtree.",
  prerequisites: [],
  related: ["next-file-conventions"],
  isHighYield: true,
  oneLiner: "Error boundaries catch render/lifecycle errors in descendants, not events, not async unless you rethrow into render. In Next, error.tsx is a boundary per segment. Use them to isolate widgets. Class component or react-error-boundary library.",
  beats: ["Render errors only (classic).", "reset() remounts.", "Log then fallback UI."],
  intro: "React interview staple; Next wraps it.",
  why: "One widget must not white-screen the app.",
  concept: "componentDidCatch / getDerivedStateFromError.",
  how: "error.tsx or <ErrorBoundary fallback>.",
  usage: "Charts, third-party widgets.",
  practices: "Boundary per feature, not one global only.",
  mistakes: "Expecting boundaries to catch async fetch without rethrow.",
  language: "typescript",
  caption: "Error boundaries",
  code: "\"use client\";\nexport default function Error({ reset }: { reset: () => void }) {\n  return <button type=\"button\" onClick={() => reset()}>Retry</button>;\n}\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-boundaries.svg",
      alt: "Error boundaries",
      caption: "Error boundaries",
    },
  ],
  examples: [
    {
      id: "isolate",
      title: "Isolate",
      about: "Dashboard widgets.",
      language: "typescript",
      code: "<ErrorBoundary fallback={<WidgetDown />}>\n  <RevenueChart />\n</ErrorBoundary>\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-promises",
  title: "Unhandled rejections",
  order: 3,
  summary: "Every promise needs a path.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Unhandled rejections crash some Node versions and are silent-ish in browsers. Await in try/catch, or .catch that reports. void promise is a smell unless you attach catch. Don't fire-and-forget in event handlers.",
  beats: ["No floating promises.", "Report + recover.", "Abort on unmount if you setState."],
  intro: "JS interview that shows up in production.",
  why: "Lost failures.",
  concept: "Promise rejection events.",
  how: "eslint @typescript-eslint/no-floating-promises.",
  usage: "Click handlers, effects.",
  practices: "Central reportRejection.",
  mistakes: "void fetch().then(setData). Empty catch.",
  language: "typescript",
  caption: "Unhandled rejections",
  code: "void load().catch(report);\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-promises.svg",
      alt: "Unhandled rejections",
      caption: "Unhandled rejections",
    },
  ],
  examples: [
    {
      id: "evt",
      title: "window handler",
      about: "Last resort logger.",
      language: "typescript",
      code: "window.addEventListener(\"unhandledrejection\", (e) => report(e.reason));\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-http",
  title: "HTTP error handling",
  order: 4,
  summary: "Status codes, problem+json, and retries.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Treat 4xx as caller mistakes (show message), 5xx and 429 as potentially transient. Parse bodies safely. Don't retry 400/401/403. Honor Retry-After. Map 401 to sign-in, 403 to forbidden UI, 404 to notFound().",
  beats: ["Idempotent retries only.", "401 vs 403.", "Never retry POST blindly."],
  intro: "Frontend meets backend contract.",
  why: "Double-charge vs lost save.",
  concept: "Status + typed error body.",
  how: "if (!res.ok) throw new HttpError(res.status, await res.json().catch(() => null))",
  usage: "fetch, RSC loaders.",
  practices: "Correlation IDs in logs.",
  mistakes: "res.json() on empty 204. Retrying 500 on create-order.",
  language: "typescript",
  caption: "HTTP error handling",
  code: "if (res.status === 401) redirect(\"/login\");\nif (res.status === 404) notFound();\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-http.svg",
      alt: "HTTP error handling",
      caption: "HTTP error handling",
    },
  ],
  examples: [
    {
      id: "retry",
      title: "GET retry",
      about: "Backoff.",
      language: "typescript",
      code: "await retry(() => fetch(url), { retries: 3, methods: [\"GET\"] });\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-ux",
  title: "User-facing failure",
  order: 5,
  summary: "Inline, toast, banner, or full page—on purpose.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Match severity to UI: field errors inline, save failures next to the button, outages as banners, catastrophic as a full page with retry and support code. Don't toast a form validation. Don't full-page a failed like button.",
  beats: ["Proximity to the action.", "Recover CTA.", "Stable copy, not stack traces."],
  intro: "Product sense in interviews.",
  why: "Users blame themselves if the message is bad.",
  concept: "Error design system.",
  how: "Reuse Alert patterns. Include an id for support.",
  usage: "All flows.",
  practices: "Write copy for offline vs our bug vs their input.",
  mistakes: "alert(). Only console.error. Red screens of death in prod.",
  language: "html",
  caption: "User-facing failure",
  code: "<p role=\"alert\">Could not save. <button type=\"button\" onClick={retry}>Try again</button></p>\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-ux.svg",
      alt: "User-facing failure",
      caption: "User-facing failure",
    },
  ],
  examples: [
    {
      id: "id",
      title: "Support code",
      about: "Show the telemetry id.",
      language: "typescript",
      code: "Something went wrong (ref {errorId})\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-retries",
  title: "Retries and backoff",
  order: 6,
  summary: "Exponential backoff, jitter, idempotency.",
  prerequisites: [],
  related: ["eh-circuit-breaker"],
  isHighYield: true,
  oneLiner: "Retry transient failures (network, 503, 429) with exponential backoff and jitter so you don't thundering-herd. Mutations need idempotency keys. Cap retries. Circuit-break if the dependency is down.",
  beats: ["Jitter.", "Idempotent POST or don't retry.", "Give up and tell the user."],
  intro: "Distributed systems lite for FE.",
  why: "Outages get worse without jitter.",
  concept: "Retry budget.",
  how: "libraries or a 15-line helper.",
  usage: "Mobile clients, flaky APIs.",
  practices: "Honor Retry-After. Don't retry in a tight loop in render.",
  mistakes: "retry 10 times immediately. Retry createCharge.",
  language: "typescript",
  caption: "Retries and backoff",
  code: "const delay = 2 ** attempt * 100 + Math.random() * 100;\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-retries.svg",
      alt: "Retries and backoff",
      caption: "Retries and backoff",
    },
  ],
  examples: [
    {
      id: "idem",
      title: "Idempotency-Key",
      about: "Payments.",
      language: "typescript",
      code: "headers: { \"Idempotency-Key\": crypto.randomUUID() }\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-timeouts",
  title: "Timeouts and abort",
  order: 7,
  summary: "Every fetch needs a deadline.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "A request without a timeout is a hung UI. Use AbortSignal.timeout or AbortController in effects. Cancel on unmount/navigation. Server: don't wait forever on downstream. Show a specific timeout message.",
  beats: ["Deadline per call.", "Abort stale.", "Don't ignore AbortError as a bug."],
  intro: "Classic race interview.",
  why: "Spinners forever.",
  concept: "Cancellation tokens.",
  how: "signal: AbortSignal.timeout(8000)",
  usage: "Search-as-you-type, RSC fetch.",
  practices: "Map AbortError to 'canceled' not Sentry noise if user navigated.",
  mistakes: "Ignoring abort. One global 5-minute timeout for everything.",
  language: "typescript",
  caption: "Timeouts and abort",
  code: "await fetch(url, { signal: AbortSignal.timeout(8_000) });\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-timeouts.svg",
      alt: "Timeouts and abort",
      caption: "Timeouts and abort",
    },
  ],
  examples: [
    {
      id: "effect",
      title: "Effect cleanup",
      about: "Abort on unmount.",
      language: "typescript",
      code: "useEffect(() => {\n  const c = new AbortController();\n  load({ signal: c.signal });\n  return () => c.abort();\n}, []);\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-partial",
  title: "Partial failure",
  order: 8,
  summary: "Render what you have; degrade the rest.",
  prerequisites: [],
  related: ["next-streaming"],
  isHighYield: false,
  oneLiner: "Dashboards should not 500 because one widget failed. Isolate fetches (Suspense + error boundary per widget). Show stale data with a warning if you have it. Feature-flag the broken widget off.",
  beats: ["Bulkheads.", "Stale > empty if honest.", "Don't block the page on a vanity metric."],
  intro: "Senior UX/architecture.",
  why: "Availability.",
  concept: "Independent failure domains.",
  how: "Promise.allSettled for independent widgets.",
  usage: "Home dashboards.",
  practices: "Degraded mode copy.",
  mistakes: "One failing request fails the whole RSC page without boundaries.",
  language: "typescript",
  caption: "Partial failure",
  code: "const [a, b] = await Promise.allSettled([loadA(), loadB()]);\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-partial.svg",
      alt: "Partial failure",
      caption: "Partial failure",
    },
  ],
  examples: [
    {
      id: "stale",
      title: "Stale",
      about: "Cache with a timestamp.",
      language: "typescript",
      code: "Updated 12m ago. Refresh failed.\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-next-error",
  title: "Next.js error.tsx and global-error",
  order: 9,
  summary: "Segment errors vs root html crash.",
  prerequisites: [],
  related: ["next-file-conventions"],
  isHighYield: true,
  oneLiner: "error.tsx handles errors in that segment and nested, as a Client Component. global-error.tsx replaces the root layout when the root fails (must include html/body). not-found is not an error. thrown errors in Server Components bubble to the nearest error.tsx.",
  beats: ["global-error is the last resort.", "reset remounts the segment.", "Log the digest in prod."],
  intro: "Next-specific handling.",
  why: "White screen vs recoverable panel.",
  concept: "File conventions = boundaries.",
  how: "Throw in a Server Component to demo.",
  usage: "App Router apps.",
  practices: "digest for support; don't leak stacks in prod UI.",
  mistakes: "Using pages/_error patterns in app/.",
  language: "typescript",
  caption: "Next.js error.tsx and global-error",
  code: "export default function GlobalError({ error }: { error: Error }) {\n  return (\n    <html>\n      <body>\n        <p>App crashed</p>\n      </body>\n    </html>\n  );\n}\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-next.svg",
      alt: "Next.js error.tsx and global-error",
      caption: "Next.js error.tsx and global-error",
    },
  ],
  examples: [
    {
      id: "digest",
      title: "digest",
      about: "Prod error id from Next.",
      language: "typescript",
      code: "console.error(error.digest);\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-logging",
  title: "Logging vs alerting",
  order: 10,
  summary: "What belongs in Sentry vs metrics vs logs.",
  prerequisites: [],
  related: ["bp-observability"],
  isHighYield: false,
  oneLiner: "Logs are for after-the-fact debugging; metrics for SLOs; alerts for human waking. Don't alert on each 404. Don't log PII. Sample high-volume client errors. Include route, release, and correlation id.",
  beats: ["Alert on rate and impact.", "Logs are not dashboards.", "Cardinality kills metrics."],
  intro: "Ops sense.",
  why: "Pager fatigue vs blindness.",
  concept: "Three pillars, used on purpose.",
  how: "error.rate > x for 5m on checkout.",
  usage: "On-call.",
  practices: "Budget: only money-path alerts at night.",
  mistakes: "Sentry for every console.warn. Unique metric per user id.",
  language: "typescript",
  caption: "Logging vs alerting",
  code: "logger.error(\"order_fail\", { orderId, requestId });\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-logging.svg",
      alt: "Logging vs alerting",
      caption: "Logging vs alerting",
    },
  ],
  examples: [
    {
      id: "sample",
      title: "Sample",
      about: "Client 1%.",
      language: "typescript",
      code: "if (Math.random() < 0.01) report(e);\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-recovery",
  title: "Recovery UX",
  order: 11,
  summary: "Retry, undo, save drafts, and conflict.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "After failure, offer a next step: retry, save draft, copy payload, contact support. For edits, keep the user's input. For conflicts (409), show both versions. Don't wipe a 20-field form on 500.",
  beats: ["Preserve input.", "Idempotent retry button.", "409 needs a merge story."],
  intro: "Product + engineering.",
  why: "Data loss is the real outage.",
  concept: "State machines: dirty, saving, saved, error.",
  how: "Keep form state outside the failing fetch.",
  usage: "Settings, editors.",
  practices: "localStorage drafts for long forms (careful with PII).",
  mistakes: "setState({}) on error. Retry that double-submits payments.",
  language: "typescript",
  caption: "Recovery UX",
  code: "const [draft, setDraft] = useState(initial);\n// on error, draft remains\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-recovery.svg",
      alt: "Recovery UX",
      caption: "Recovery UX",
    },
  ],
  examples: [
    {
      id: "409",
      title: "Conflict",
      about: "Reload + keep local.",
      language: "typescript",
      code: "showConflict({ server, local });\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-validation",
  title: "Validation errors",
  order: 12,
  summary: "Schema at the edge; messages at the field.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Validation is expected failure. Use a schema (Zod) on client and server (never client-only). Map issues to fields. Don't 500 on bad input. Accessibility: aria-invalid and error ids.",
  beats: ["Server is source of truth.", "Field-level copy.", "Same schema both sides if you can."],
  intro: "Forms interviews.",
  why: "Users can fix these—help them.",
  concept: "Parse vs validate.",
  how: "useActionState + Zod flatten.",
  usage: "Any form.",
  practices: "Disable submit while pending, not forever after one error.",
  mistakes: "Only client validation. Vague 'invalid' with no field.",
  language: "html",
  caption: "Validation errors",
  code: "const parsed = Schema.safeParse(input);\nif (!parsed.success) return { fieldErrors: parsed.error.flatten().fieldErrors };\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-validation.svg",
      alt: "Validation errors",
      caption: "Validation errors",
    },
  ],
  examples: [
    {
      id: "a11y",
      title: "aria-describedby",
      about: "Connect input to error.",
      language: "typescript",
      code: "<input aria-invalid aria-describedby=\"email-err\" />\n<p id=\"email-err\">Use a work email</p>\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-offline",
  title: "Offline and network loss",
  order: 13,
  summary: "Detect, queue, and don't lie.",
  prerequisites: [],
  related: ["pwa-overview"],
  isHighYield: false,
  oneLiner: "navigator.onLine is a hint, not truth. Failed fetch + timeout is the real signal. Tell the user they're offline, queue non-critical actions if you have a PWA story, and don't show optimistic success you cannot sync.",
  beats: ["Honest status.", "Queue with conflict rules.", "Retry when online fires."],
  intro: "PWA + error handling overlap.",
  why: "Field tools and travel.",
  concept: "Online event + request errors.",
  how: "Listen to online; still try the request.",
  usage: "Drafts, likes.",
  practices: "Outbox pattern for serious offline.",
  mistakes: "Optimistic UI without rollback. Trusting onLine alone.",
  language: "typescript",
  caption: "Offline and network loss",
  code: "window.addEventListener(\"online\", flushQueue);\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-offline.svg",
      alt: "Offline and network loss",
      caption: "Offline and network loss",
    },
  ],
  examples: [
    {
      id: "banner",
      title: "Banner",
      about: "You appear offline.",
      language: "typescript",
      code: "<div role=\"status\">Offline. We'll retry when you're back.</div>\n",
    }
  ],
}),

errorHandlingTopic({
  slug: "eh-circuit-breaker",
  title: "Circuit breakers",
  order: 14,
  summary: "Stop calling a dead dependency.",
  prerequisites: [],
  related: ["eh-retries"],
  isHighYield: false,
  oneLiner: "If a service errors past a threshold, fail fast for a cooldown (open circuit), then probe (half-open). Protects your origin and the dependency. On the frontend, disable a widget and skip fetch. On the BFF, return a cached/degraded payload.",
  beats: ["Fail fast when open.", "Half-open probe.", "User-visible degraded mode."],
  intro: "Expert-level handling.",
  why: "Cascading failures.",
  concept: "Closed → open → half-open.",
  how: "Tiny in-memory breaker per session or server singleton.",
  usage: "Chat, recommendations, ads.",
  practices: "Alert when a circuit opens.",
  mistakes: "Retry storms. One global breaker for all APIs.",
  language: "typescript",
  caption: "Circuit breakers",
  code: "if (breaker.isOpen(\"recs\")) return <RecsUnavailable />;\n",
  figures: [
    {
      src: "/diagrams/error-handling/eh-circuit-breaker.svg",
      alt: "Circuit breakers",
      caption: "Circuit breakers",
    },
  ],
  examples: [
    {
      id: "probe",
      title: "Probe",
      about: "One request after cooldown.",
      language: "typescript",
      code: "breaker.allowRequest() && loadRecs()\n",
    }
  ],
}),
];
