import type { Topic } from "../../types";
import { securityTopic } from "./factory";

export const securityCurriculumTopics: Topic[] = [
securityTopic({
  slug: "sec-xss",
  title: "Cross-site scripting",
  order: 1,
  summary: "Sinks, encoding, and why React is not a silver bullet.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "XSS is injecting script into a victim's origin. React encodes text content by default, but dangerouslySetInnerHTML, href javascript:, and unsanitized markdown are sinks. Encode for the context (HTML, attr, URL, JS). Sanitize HTML with a vetted library if you must render it.",
  beats: ["Context-aware encoding.", "Don't roll a sanitizer.", "CSP is defense in depth, not the first control."],
  intro: "The #1 frontend security interview.",
  why: "Session theft and defacement.",
  concept: "Source → sink. Trusted types if available.",
  how: "Never assign user HTML to innerHTML.",
  usage: "Comments, markdown, rich text.",
  practices: "CSP nonce for your scripts. Audit markdown.",
  mistakes: "Blacklist <script>. URL from user into iframe src.",
  language: "typescript",
  caption: "Cross-site scripting",
  code: "const safe = user.name; // text child is encoded\n<div dangerouslySetInnerHTML={{ __html: sanitize(html) }} />\n",
  figures: [
    {
      src: "/diagrams/security/sec-xss.svg",
      alt: "Cross-site scripting",
      caption: "Cross-site scripting",
    },
  ],
  examples: [
    {
      id: "href",
      title: "javascript: URLs",
      about: "Allowlist http(s).",
      language: "typescript",
      code: "function safeHref(url: string) {\n  const u = new URL(url, \"https://example.com\");\n  if (u.protocol !== \"http:\" && u.protocol !== \"https:\") return \"#\";\n  return u.href;\n}\n",
    }
  ],
}),

securityTopic({
  slug: "sec-csp",
  title: "Content Security Policy",
  order: 2,
  summary: "Allowlists, nonces, and strict-dynamic.",
  prerequisites: [],
  related: ["sec-xss"],
  isHighYield: true,
  oneLiner: "CSP tells the browser which scripts/styles/connect targets are allowed. A strict CSP uses nonces or hashes, not origin soup. 'unsafe-inline' defeats script CSP. Report-Only first. CSP does not fix XSS by itself if you allow unsafe-inline.",
  beats: ["Nonce or hash.", "No unsafe-inline for scripts.", "connect-src for APIs."],
  intro: "Defense-in-depth interview.",
  why: "Lowers XSS impact.",
  concept: "Policy delivered via header (prefer) or meta.",
  how: "Next: headers() in next.config or middleware.",
  usage: "Any production app.",
  practices: "Iterate with report-uri/report-to.",
  mistakes: "Copy-pasting unsafe-eval to silence errors.",
  language: "html",
  caption: "Content Security Policy",
  code: "Content-Security-Policy: default-src 'self'; script-src 'nonce-abc' 'strict-dynamic'\n",
  figures: [
    {
      src: "/diagrams/security/sec-csp.svg",
      alt: "Content Security Policy",
      caption: "Content Security Policy",
    },
  ],
  examples: [
    {
      id: "report",
      title: "Report-Only",
      about: "Measure breakage.",
      language: "typescript",
      code: "Content-Security-Policy-Report-Only: …\n",
    }
  ],
}),

securityTopic({
  slug: "sec-csrf",
  title: "CSRF",
  order: 3,
  summary: "Cookie auth + cross-site POST.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "CSRF tricks the browser into sending cookies to your origin from another site. SameSite=Lax/Strict cookies reduce it. Origin/Referer checks and anti-CSRF tokens help for state-changing requests. SameSite is not enough for all subdomain/lax cases. Bearer tokens in headers are not sent automatically cross-site.",
  beats: ["Cookie-authenticated POST is the classic.", "SameSite + Origin check.", "GET must stay safe."],
  intro: "Still asked even with SameSite.",
  why: "Unwanted transfers and email-change.",
  concept: "Cross-site request with ambient credentials.",
  how: "Framework CSRF for cookie sessions. Next Actions check Origin.",
  usage: "Form posts, cookie sessions.",
  practices: "Don't use GET for mutations.",
  mistakes: "JSON APIs with cookies and no Origin check. CORS * with credentials.",
  language: "typescript",
  caption: "CSRF",
  code: "if (req.headers.get(\"origin\") !== allowed) return new Response(null, { status: 403 });\n",
  figures: [
    {
      src: "/diagrams/security/sec-csrf.svg",
      alt: "CSRF",
      caption: "CSRF",
    },
  ],
  examples: [
    {
      id: "samesite",
      title: "SameSite",
      about: "Lax default for sessions.",
      language: "typescript",
      code: "Set-Cookie: sid=…; SameSite=Lax; Secure; HttpOnly\n",
    }
  ],
}),

securityTopic({
  slug: "sec-cors",
  title: "CORS",
  order: 4,
  summary: "Browser-enforced, not a server firewall.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "CORS is a browser policy for JS reading cross-origin responses. Servers send ACAO headers. It is not access control for native apps or curl. Credentials mode cannot use *. Preflight exists for 'non-simple' requests. Don't 'fix' APIs by reflecting any Origin.",
  beats: ["Browsers only.", "Never * with credentials.", "Allowlist origins."],
  intro: "Constant FE/BE interview.",
  why: "Misconfig leaks private APIs to hostile pages.",
  concept: "Simple vs preflighted requests.",
  how: "Server allowlist. BFF to avoid browser CORS.",
  usage: "SPAs on another origin.",
  practices: "Same-site via reverse proxy when possible.",
  mistakes: "Access-Control-Allow-Origin: * on authenticated APIs.",
  language: "html",
  caption: "CORS",
  code: "Access-Control-Allow-Origin: https://app.example.com\nAccess-Control-Allow-Credentials: true\n",
  figures: [
    {
      src: "/diagrams/security/sec-cors.svg",
      alt: "CORS",
      caption: "CORS",
    },
  ],
  examples: [
    {
      id: "bff",
      title: "BFF",
      about: "Browser talks same origin.",
      language: "typescript",
      code: "// /api on the Next host proxies the private API\n",
    }
  ],
}),

securityTopic({
  slug: "sec-auth",
  title: "Auth attacks on the client",
  order: 5,
  summary: "Token storage, XSS theft, and session fixation.",
  prerequisites: [],
  related: ["sec-cookies"],
  isHighYield: true,
  oneLiner: "If XSS can read it, it's stolen: localStorage tokens are XSS-complete. Prefer HttpOnly cookies for sessions. Refresh tokens need rotation. Don't put JWTs in URLs. Session fixation: issue a new session id at login. Frontend authz UI is UX, not security.",
  beats: ["HttpOnly session cookies.", "UI hiding is not authz.", "Rotate refresh tokens."],
  intro: "Always asked.",
  why: "Account takeover.",
  concept: "Credential types: cookies vs bearer.",
  how: "Set session cookie from server; CSRF controls apply.",
  usage: "SPA login, OAuth popups.",
  practices: "Short access tokens. Audience/issuer checks on the server.",
  mistakes: "JWT in localStorage 'because SPA'. Trusting role in the JWT payload on the client only.",
  language: "typescript",
  caption: "Auth attacks on the client",
  code: "document.cookie; // cannot read HttpOnly\n",
  figures: [
    {
      src: "/diagrams/security/sec-auth.svg",
      alt: "Auth attacks on the client",
      caption: "Auth attacks on the client",
    },
  ],
  examples: [
    {
      id: "fix",
      title: "Fixation",
      about: "Regenerate id.",
      language: "typescript",
      code: "// server: destroy anonymous session, issue new sid at login\n",
    }
  ],
}),

securityTopic({
  slug: "sec-cookies",
  title: "Cookie flags",
  order: 6,
  summary: "Secure, HttpOnly, SameSite, Prefix, Partitioned.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Cookie security is flags: Secure (HTTPS), HttpOnly (no JS), SameSite, Path/Domain scoped tightly, __Host- prefix (Secure + Path=/ + no Domain), Partitioned for third-party CHIPS. Domain=.example.com is wide—avoid if you can.",
  beats: ["Tightest Domain/Path.", "__Host- when you can.", "No sensitive cookies on http."],
  intro: "Checklist interview.",
  why: "Flags are free wins.",
  concept: "Browser cookie jar rules.",
  how: "Set from Set-Cookie on the session response.",
  usage: "Sessions, CSRF tokens (not HttpOnly if double-submit).",
  practices: "Document cookie inventory.",
  mistakes: "Domain=.com. Missing Secure in prod.",
  language: "html",
  caption: "Cookie flags",
  code: "Set-Cookie: __Host-session=…; Secure; HttpOnly; Path=/; SameSite=Lax\n",
  figures: [
    {
      src: "/diagrams/security/sec-cookies.svg",
      alt: "Cookie flags",
      caption: "Cookie flags",
    },
  ],
  examples: [
    {
      id: "name",
      title: "Prefixes",
      about: "__Secure- requires Secure.",
      language: "typescript",
      code: "__Secure-csrf=…; Secure; SameSite=Strict\n",
    }
  ],
}),

securityTopic({
  slug: "sec-secrets",
  title: "Secrets and the client bundle",
  order: 7,
  summary: "If it's in the JS, it's public.",
  prerequisites: [],
  related: ["next-env"],
  isHighYield: true,
  oneLiner: "Anything in a Client Component or NEXT_PUBLIC_ is public. Map keys with HTTP referrer restrictions, not secrecy. Server secrets stay in Server Components, actions, and route handlers. Review source maps and error reports for leaked env.",
  beats: ["Public vs secret.", "Referrer-restricted API keys.", "No secrets in repo or CI logs."],
  intro: "Next-specific security.",
  why: "Cloud bills and data leaks.",
  concept: "Bundler inlining.",
  how: "server-only import; env validation.",
  usage: "Stripe, maps, analytics.",
  practices: "Rotate on leak. Pre-commit secret scan.",
  mistakes: "Firebase admin key in the app. Commit .env.",
  language: "typescript",
  caption: "Secrets and the client bundle",
  code: "import \"server-only\";\nexport const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);\n",
  figures: [
    {
      src: "/diagrams/security/sec-secrets.svg",
      alt: "Secrets and the client bundle",
      caption: "Secrets and the client bundle",
    },
  ],
  examples: [
    {
      id: "maps",
      title: "Public key",
      about: "Restrict by referrer.",
      language: "typescript",
      code: "NEXT_PUBLIC_MAPS_KEY is still public\n",
    }
  ],
}),

securityTopic({
  slug: "sec-deps",
  title: "Supply chain",
  order: 8,
  summary: "Lockfiles, pinning, and install scripts.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "You run publisher code at install (postinstall) and at runtime. Use lockfiles, ignore-scripts when you can, review sudden version jumps, and pin GitHub Actions. npm audit is a start, not a program. Compromised maintainer is a real interview story.",
  beats: ["Lockfile committed.", "Review postinstall.", "Pin actions by SHA."],
  intro: "Industry-current topic.",
  why: "One package can steal tokens from CI.",
  concept: "Graph of dependencies.",
  how: "pnpm + ignore-scripts + allowlist.",
  usage: "CI, app runtime.",
  practices: "Diff lockfile in PRs. Provenance when available.",
  mistakes: "npm i latest on prod. Blind --force.",
  language: "typescript",
  caption: "Supply chain",
  code: "pnpm config set ignore-scripts true\n",
  figures: [
    {
      src: "/diagrams/security/sec-deps.svg",
      alt: "Supply chain",
      caption: "Supply chain",
    },
  ],
  examples: [
    {
      id: "ci",
      title: "CI tokens",
      about: "Least privilege.",
      language: "typescript",
      code: "// don't expose npm token to untrusted PRs\n",
    }
  ],
}),

securityTopic({
  slug: "sec-privacy",
  title: "Privacy and PII",
  order: 9,
  summary: "What you store in the client and send to analytics.",
  prerequisites: [],
  related: ["perf-third-party"],
  isHighYield: false,
  oneLiner: "PII in the client (localStorage profiles, URL emails) leaks via XSS, support screenshots, and analytics. Minimize. Hash or omit. Consent for non-essential cookies. Don't put secrets or government IDs in events.",
  beats: ["Data minimization.", "Consent.", "Retention."],
  intro: "Legal + security interviews.",
  why: "GDPR/CCPA and user trust.",
  concept: "Client storage + third-party pixels.",
  how: "Allowlist event properties.",
  usage: "Analytics, error reporting.",
  practices: "Drop IP in logs when you can. Mask emails.",
  mistakes: "Full form payloads to analytics. User email in the URL.",
  language: "typescript",
  caption: "Privacy and PII",
  code: "track(\"purchase\", { amount, plan }); // no email, no card\n",
  figures: [
    {
      src: "/diagrams/security/sec-privacy.svg",
      alt: "Privacy and PII",
      caption: "Privacy and PII",
    },
  ],
  examples: [
    {
      id: "url",
      title: "URLs",
      about: "Tokens in query strings leak via Referer.",
      language: "typescript",
      code: "// use POST body or fragment carefully; prefer headers\n",
    }
  ],
}),

securityTopic({
  slug: "sec-clickjacking",
  title: "Clickjacking and framing",
  order: 10,
  summary: "X-Frame-Options and CSP frame-ancestors.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Clickjacking overlays your UI in an iframe so users click 'Buy' on the attacker's page. Deny framing with CSP frame-ancestors 'self' or 'none', and X-Frame-Options DENY as legacy. If you must embed, allowlist ancestors.",
  beats: ["frame-ancestors is the modern control.", "Don't rely on JS frame-busting.", "Embedded widgets need a deliberate policy."],
  intro: "Classic but still real for banks and admin.",
  why: "Unintended actions.",
  concept: "Iframe overlay.",
  how: "Set headers globally.",
  usage: "Admin apps, payments.",
  practices: "Document who may embed you.",
  mistakes: "Allowing * framing. Busting with JS only.",
  language: "html",
  caption: "Clickjacking and framing",
  code: "Content-Security-Policy: frame-ancestors 'none'\n",
  figures: [
    {
      src: "/diagrams/security/sec-clickjacking.svg",
      alt: "Clickjacking and framing",
      caption: "Clickjacking and framing",
    },
  ],
  examples: [
    {
      id: "xfo",
      title: "Legacy",
      about: "X-Frame-Options: DENY",
      language: "typescript",
      code: "X-Frame-Options: DENY\n",
    }
  ],
}),

securityTopic({
  slug: "sec-redirect",
  title: "Open redirects",
  order: 11,
  summary: "User-controlled next= URLs.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Open redirects send users to attacker sites with your origin as the trampoline (phishing). Allowlist paths: only relative paths on your origin, or a map of known names. Never redirect to a raw user URL.",
  beats: ["Allowlist.", "Relative paths only.", "Watch //evil.com tricks."],
  intro: "Login next= parameter is the example.",
  why: "Phishing with your brand.",
  concept: "302 to untrusted destination.",
  how: "new URL(path, origin) and check origin.",
  usage: "OAuth redirect_uri, login bounce.",
  practices: "Protocol-relative URLs. Backslash tricks.",
  mistakes: "redirect('https://evil.example') from query.",
  language: "typescript",
  caption: "Open redirects",
  code: "function safeNext(path: string) {\n  if (!path.startsWith(\"/\") || path.startsWith(\"//\")) return \"/home\";\n  return path;\n}\n",
  figures: [
    {
      src: "/diagrams/security/sec-redirect.svg",
      alt: "Open redirects",
      caption: "Open redirects",
    },
  ],
  examples: [
    {
      id: "proto",
      title: "protocol-relative",
      about: "//evil.com is not a path.",
      language: "typescript",
      code: "// startsWith('/') is not enough if '//'\n",
    }
  ],
}),

securityTopic({
  slug: "sec-authz",
  title: "Authorization vs authentication",
  order: 12,
  summary: "UI gates are not server gates.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Authentication is who you are; authorization is what you may do. Hiding a button does nothing. Every Server Action, route handler, and loader must check the resource belongs to the user (or their role). IDOR is the bug: incrementing /api/orders/41.",
  beats: ["Check on the server.", "Object-level authz.", "Roles ≠ row access."],
  intro: "Most 'hacks' in homework apps are IDOR.",
  why: "Data leaks.",
  concept: "ACL/policy at the domain layer.",
  how: "Load the row, then assert ownerId === session.userId.",
  usage: "Multi-tenant SaaS.",
  practices: "Tests that call actions as another user.",
  mistakes: "Trusting hidden form fields for price or ownerId.",
  language: "typescript",
  caption: "Authorization vs authentication",
  code: "const order = await db.order.find(id);\nif (order.userId !== user.id) throw new Error(\"forbidden\");\n",
  figures: [
    {
      src: "/diagrams/security/sec-authz.svg",
      alt: "Authorization vs authentication",
      caption: "Authorization vs authentication",
    },
  ],
  examples: [
    {
      id: "idor",
      title: "IDOR",
      about: "Guessable IDs.",
      language: "typescript",
      code: "// prefer opaque IDs; still check ownership\n",
    }
  ],
}),

securityTopic({
  slug: "sec-ssrf",
  title: "SSRF from the Next server",
  order: 13,
  summary: "User URLs fetched by the server.",
  prerequisites: [],
  related: ["next-image-font"],
  isHighYield: true,
  oneLiner: "If a Server Component or image optimizer fetches a user-supplied URL, attackers can hit internal IPs (metadata services, admin). Allowlist hosts, block link-local/private ranges, and disable follow to file://. Next's image optimizer remotePatterns is this control.",
  beats: ["Allowlist outbound hosts.", "No user URL to fetch unchecked.", "Cloud metadata IPs."],
  intro: "Modern Next interview, not just backend.",
  why: "Cloud credential theft.",
  concept: "Server-side request with attacker URL.",
  how: "URL parse + allowlist hostname.",
  usage: "Link unfurl, OG fetch, image proxy.",
  practices: "Disable unused optimizer. Network egress policies.",
  mistakes: "fetch(req.query.url). Preview of file://.",
  language: "typescript",
  caption: "SSRF from the Next server",
  code: "const allowed = new Set([\"cdn.example.com\"]);\nif (!allowed.has(new URL(url).hostname)) throw new Error(\"host\");\n",
  figures: [
    {
      src: "/diagrams/security/sec-ssrf.svg",
      alt: "SSRF from the Next server",
      caption: "SSRF from the Next server",
    },
  ],
  examples: [
    {
      id: "img",
      title: "remotePatterns",
      about: "Image optimizer allowlist.",
      language: "typescript",
      code: "images: { remotePatterns: [{ hostname: \"images.example.com\" }] }\n",
    }
  ],
}),

securityTopic({
  slug: "sec-headers",
  title: "Security headers",
  order: 14,
  summary: "A baseline header set for HTML origins.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Besides CSP and framing: HSTS, Referrer-Policy, X-Content-Type-Options nosniff, Permissions-Policy, COOP/COEP if you need isolation. Headers are cheap. Set them in the host or Next headers config, not only on some routes.",
  beats: ["HSTS once HTTPS is sure.", "nosniff.", "Permissions-Policy to disable unused APIs."],
  intro: "Checklist for seniors.",
  why: "Defense in depth.",
  concept: "Browser security features gated by headers.",
  how: "next.config headers() or CDN.",
  usage: "All HTML responses.",
  practices: "Report-Only CSP first. Staging != prod HSTS preload until ready.",
  mistakes: "Copying a 2014 header blog with XSS-Protection.",
  language: "html",
  caption: "Security headers",
  code: "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload\nX-Content-Type-Options: nosniff\nReferrer-Policy: strict-origin-when-cross-origin\n",
  figures: [
    {
      src: "/diagrams/security/sec-headers.svg",
      alt: "Security headers",
      caption: "Security headers",
    },
  ],
  examples: [
    {
      id: "pp",
      title: "Permissions-Policy",
      about: "Disable camera by default.",
      language: "typescript",
      code: "Permissions-Policy: camera=(), microphone=(), geolocation=()\n",
    }
  ],
}),
];
