import type { Topic } from "../../types";
import { performanceTopic } from "./factory";

export const performanceCurriculumTopics: Topic[] = [
performanceTopic({
  slug: "perf-cwv",
  title: "Core Web Vitals",
  order: 1,
  summary: "LCP, INP, CLS: what they measure and the thresholds.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Core Web Vitals are field metrics: LCP (loading), INP (interactivity), CLS (visual stability). Good thresholds are moving targets—quote the current Google bins (good/needs-improvement/poor) and how you debug lab vs field (CrUX, RUM).",
  beats: ["LCP: largest paint in viewport.", "INP: latency of interactions across the page life.", "CLS: unexpected layout shift."],
  intro: "Every performance interview starts here in 2026.",
  why: "SEO and UX share these numbers.",
  concept: "Lab (Lighthouse) ≠ field (RUM). Optimize for field.",
  how: "Measure on a real device + 4G. Then profile.",
  usage: "Any public site.",
  practices: "Attribute LCP element. Don't chase scores with tricks that hurt UX.",
  mistakes: "Hiding LCP to game the metric. Ignoring INP because FID is gone.",
  language: "typescript",
  caption: "Core Web Vitals",
  code: "web-vitals: onINP, onLCP, onCLS → send to RUM\n",
  figures: [
    {
      src: "/diagrams/performance/perf-cwv.svg",
      alt: "Core Web Vitals",
      caption: "Core Web Vitals",
    },
  ],
  examples: [
    {
      id: "attr",
      title: "LCP element",
      about: "Often a hero image or H1.",
      language: "typescript",
      code: "new PerformanceObserver((list) => {\n  const last = list.getEntries().at(-1);\n  console.log(last);\n}).observe({ type: \"largest-contentful-paint\", buffered: true });\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-lcp",
  title: "LCP in practice",
  order: 2,
  summary: "Hero image, fonts, TTFB, and discoverability.",
  prerequisites: ["perf-cwv"],
  related: [],
  isHighYield: true,
  oneLiner: "LCP is usually a hero image, a poster, or large text. Improve TTFB (SSR/cache), discover the image early (preload, not lazy), size it, use a modern format, and don't delay it behind client fetch. Fonts can delay text LCP.",
  beats: ["Don't lazy-load the LCP image.", "priority / fetchpriority=high.", "TTFB is part of LCP."],
  intro: "The most actionable CWV.",
  why: "Users bounce on slow heroes.",
  concept: "Resource timing + element timing.",
  how: "next/image priority; preload if needed.",
  usage: "Marketing, PDP.",
  practices: "Preload only the real LCP candidate.",
  mistakes: "Carousel as LCP. Client-only hero.",
  language: "typescript",
  caption: "LCP in practice",
  code: "<Image src=\"/hero.webp\" alt=\"\" width={1200} height={600} priority />\n",
  figures: [
    {
      src: "/diagrams/performance/perf-lcp.svg",
      alt: "LCP in practice",
      caption: "LCP in practice",
    },
  ],
  examples: [
    {
      id: "ttfb",
      title: "TTFB",
      about: "CDN + streaming shell.",
      language: "typescript",
      code: "// See Next streaming / PPR\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-inp",
  title: "INP and long tasks",
  order: 3,
  summary: "Interaction to next paint: break up main thread work.",
  prerequisites: ["perf-cwv"],
  related: [],
  isHighYield: true,
  oneLiner: "INP is the worst (almost) interaction delay in a session. Causes: long tasks from JS parse/eval, hydration, heavy click handlers, layout thrash. Fix: split work, yield (scheduler.yield / startTransition), reduce hydration, move work off the main thread.",
  beats: ["Long tasks >50ms compete with input.", "Hydration is JS tax.", "Measure with profiler + INP attribution."],
  intro: "FID is gone; INP is the interview metric.",
  why: "Rage clicks are INP.",
  concept: "Input delay + processing + next paint.",
  how: "Chrome performance panel; INP debug loaves.",
  usage: "Editors, dashboards, filters.",
  practices: "Debounce less; do less. Virtualize lists.",
  mistakes: "Giant JSON parse on click. Synchronous layout reads in a loop.",
  language: "typescript",
  caption: "INP and long tasks",
  code: "startTransition(() => setQuery(value));\n",
  figures: [
    {
      src: "/diagrams/performance/perf-inp.svg",
      alt: "INP and long tasks",
      caption: "INP and long tasks",
    },
  ],
  examples: [
    {
      id: "yield",
      title: "Yield",
      about: "Split a loop.",
      language: "typescript",
      code: "for (const chunk of chunks) {\n  await scheduler.yield?.();\n  process(chunk);\n}\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-cls",
  title: "Cumulative Layout Shift",
  order: 4,
  summary: "Reserve space; avoid late-loading webfonts and ads.",
  prerequisites: ["perf-cwv"],
  related: [],
  isHighYield: true,
  oneLiner: "CLS measures unexpected movement. Reserve width/height for images and embeds, use font-display strategies that don't shove text, and don't inject banners above existing content without space. Skeleton sizes should match the result.",
  beats: ["Always dimensions on media.", "Web fonts: fallback metrics / optional.", "Ads need slots."],
  intro: "Classic CSS interview with a metric name.",
  why: "Accidental taps and lost reading position.",
  concept: "Layout instability score per shift.",
  how: "aspect-ratio boxes; next/font.",
  usage: "Cookies banners, lazy images.",
  practices: "Transform animations don't cause CLS; top/left do.",
  mistakes: "Inserting a cookie banner at the top after hydrate.",
  language: "css",
  caption: "Cumulative Layout Shift",
  code: "img { aspect-ratio: 16 / 9; width: 100%; height: auto; }\n",
  figures: [
    {
      src: "/diagrams/performance/perf-cls.svg",
      alt: "Cumulative Layout Shift",
      caption: "Cumulative Layout Shift",
    },
  ],
  examples: [
    {
      id: "font",
      title: "Font fallback",
      about: "size-adjust in next/font.",
      language: "typescript",
      code: "Inter({ adjustFontFallback: true })\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-load",
  title: "Loading performance",
  order: 5,
  summary: "Code split, critical CSS, and the network waterfall.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Loading performance is bytes on the critical path: JS, CSS, fonts, hero image. Split by route, defer non-critical JS, inline tiny critical CSS if needed, and use HTTP/2+HTTP/3. Watch waterfalls in DevTools Network.",
  beats: ["Route-level split is the default in Next.", "Fewer blocking requests.", "Compression and caching headers."],
  intro: "Lighthouse 'opportunities' live here.",
  why: "First visit on 4G is the design constraint.",
  concept: "Critical path = blocking resources until first paint.",
  how: "dynamic import() for heavy editors.",
  usage: "SPAs, Next apps.",
  practices: "Analyze with Coverage and webpack-bundle-analyzer / turbopack stats.",
  mistakes: "One mega bundle. Importing lodash whole.",
  language: "typescript",
  caption: "Loading performance",
  code: "const Editor = dynamic(() => import(\"./editor\"), { ssr: false });\n",
  figures: [
    {
      src: "/diagrams/performance/perf-load.svg",
      alt: "Loading performance",
      caption: "Loading performance",
    },
  ],
  examples: [
    {
      id: "http",
      title: "Cache-Control",
      about: "Hashed static assets immutable.",
      language: "typescript",
      code: "Cache-Control: public, max-age=31536000, immutable\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-images",
  title: "Image performance",
  order: 6,
  summary: "Format, density, srcset, and CDN.",
  prerequisites: [],
  related: ["next-image-font"],
  isHighYield: false,
  oneLiner: "Serve the smallest acceptable image: AVIF/WebP with JPEG fallback, srcset for DPR, sizes for layout, compression that doesn't destroy faces. Don't ship 4000px into a 320px slot. Prefer CSS for simple graphics.",
  beats: ["sizes must match layout.", "CDN + optimizer.", "Lazy below the fold only."],
  intro: "LCP cousin.",
  why: "Images dominate bytes.",
  concept: "Responsive images spec.",
  how: "next/image or a CDN product.",
  usage: "Galleries, avatars, OG.",
  practices: "Art direction with picture. Blur placeholders carefully (bytes).",
  mistakes: "PNG screenshots as heroes. Unbounded srcset.",
  language: "html",
  caption: "Image performance",
  code: "<img srcset=\"a-640.webp 640w, a-1280.webp 1280w\" sizes=\"(max-width: 600px) 100vw, 600px\" alt=\"\" />\n",
  figures: [
    {
      src: "/diagrams/performance/perf-images.svg",
      alt: "Image performance",
      caption: "Image performance",
    },
  ],
  examples: [
    {
      id: "cdn",
      title: "CDN params",
      about: "Width in the URL.",
      language: "typescript",
      code: "cdn.example.com/img.jpg?w=800&fm=webp\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-fonts",
  title: "Font performance",
  order: 7,
  summary: "Self-host, subset, and fallback metrics.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Third-party font CSS is a classic bottleneck. Self-host (next/font), subset to used glyphs, unicode-range, and match fallback metrics to reduce CLS. font-display: optional can skip late fonts on slow networks.",
  beats: ["Self-host.", "Subset.", "Match metrics."],
  intro: "INP/LCP/CLS all can involve fonts.",
  why: "FOIT/FOUT UX.",
  concept: "@font-face pipeline.",
  how: "next/font or fonttools subset.",
  usage: "Brand typography.",
  practices: "Preload only the one critical family/weight.",
  mistakes: "Loading 12 weights. render-blocking Google CSS.",
  language: "css",
  caption: "Font performance",
  code: "@font-face { font-family: Inter; src: url(/inter.woff2) format(\"woff2\"); font-display: swap; }\n",
  figures: [
    {
      src: "/diagrams/performance/perf-fonts.svg",
      alt: "Font performance",
      caption: "Font performance",
    },
  ],
  examples: [
    {
      id: "subset",
      title: "latin only",
      about: "Don't ship every language until needed.",
      language: "typescript",
      code: "Inter({ subsets: [\"latin\"] })\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-split",
  title: "Code splitting and bundles",
  order: 8,
  summary: "Route split, dynamic import, and 'who imported moment'.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "The JS you ship is a product decision. Split by route automatically (Next). Dynamically import rare heavy widgets. Audit duplicates and CJS in ESM. Tree-shaking needs ESM and sideEffects: false done honestly.",
  beats: ["See the treemap.", "Default import of lodash is a bug.", "Server-only modules must stay server-only."],
  intro: "Senior perf interview.",
  why: "Parse/eval delay INP and TTI.",
  concept: "Graph of modules → chunks.",
  how: "@next/bundle-analyzer or source-map-explorer.",
  usage: "Any SPA.",
  practices: "Set budgets in CI (bytes per route).",
  mistakes: "Barrel files that re-export the universe. Client-importing fs.",
  language: "typescript",
  caption: "Code splitting and bundles",
  code: "import { debounce } from \"lodash-es\";\n",
  figures: [
    {
      src: "/diagrams/performance/perf-split.svg",
      alt: "Code splitting and bundles",
      caption: "Code splitting and bundles",
    },
  ],
  examples: [
    {
      id: "serveronly",
      title: "server-only",
      about: "Guard leaks.",
      language: "typescript",
      code: "import \"server-only\";\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-waterfalls",
  title: "Request waterfalls",
  order: 9,
  summary: "Sequential awaits that should be parallel.",
  prerequisites: [],
  related: ["next-data-fetching"],
  isHighYield: true,
  oneLiner: "A waterfall is await A then await B when B didn't need A's result. On the server, Promise.all. On the client, don't fetch in useEffect chains that could be one endpoint or RSC. Next: don't fetch in a child only after parent fetch if they are independent.",
  beats: ["Draw the network panel.", "Promise.all siblings.", "BFF or join in the database."],
  intro: "Classic Next/React data interview.",
  why: "TTFB death by a thousand awaits.",
  concept: "Dependency graph of data.",
  how: "Compose loaders; prefetch.",
  usage: "Dashboards, RSC trees.",
  practices: "One API for a screen when latency is high.",
  mistakes: "Waterfall: user → posts → comments each sequential.",
  language: "typescript",
  caption: "Request waterfalls",
  code: "const [a, b] = await Promise.all([loadA(), loadB()]);\n",
  figures: [
    {
      src: "/diagrams/performance/perf-waterfalls.svg",
      alt: "Request waterfalls",
      caption: "Request waterfalls",
    },
  ],
  examples: [
    {
      id: "prefetch",
      title: "Link prefetch",
      about: "App Router prefetches static.",
      language: "typescript",
      code: "<Link href=\"/dash\">Dash</Link>\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-runtime",
  title: "Runtime performance",
  order: 10,
  summary: "Re-renders, lists, and layout thrash.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "After load, runtime cost is React re-renders, layout/paint, and GC. Profile with React Profiler + Performance panel. Memoize when profiling shows waste, not by default. Virtualize huge lists. Batch DOM reads/writes.",
  beats: ["Measure first.", "Keys on lists.", "Layout thrash: read then write loops."],
  intro: "Medior+ interviews.",
  why: "Jank is churn.",
  concept: "Frames of 16ms budget (rough).",
  how: "startTransition for non-urgent sets.",
  usage: "Filters, canvases, tables.",
  practices: "content-visibility for long pages where appropriate.",
  mistakes: "Premature memo everywhere. index as key on reorderable lists.",
  language: "typescript",
  caption: "Runtime performance",
  code: "document.body.offsetHeight; // read\nel.style.height = \"10px\"; // write — don't interleave in a loop\n",
  figures: [
    {
      src: "/diagrams/performance/perf-runtime.svg",
      alt: "Runtime performance",
      caption: "Runtime performance",
    },
  ],
  examples: [
    {
      id: "virt",
      title: "Virtualize",
      about: "Window the list.",
      language: "typescript",
      code: "// react-virtual / tanstack virtual\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-hydration",
  title: "Hydration cost",
  order: 11,
  summary: "JS to make SSR interactive; reduce islands.",
  prerequisites: [],
  related: ["next-rsc-islands"],
  isHighYield: true,
  oneLiner: "Hydration attaches listeners to server HTML. Cost scales with Client Component JS. Reduce islands, delay non-critical hydration, use RSC for static parts. Mismatch (invalid HTML, dates) causes full client render.",
  beats: ["Less client JS = less hydration.", "Suppress only with cause.", "Streaming != free hydration."],
  intro: "Next-specific perf.",
  why: "INP on first interaction after load.",
  concept: "SSR HTML + JS replay.",
  how: "Selective hydration in React 18+.",
  usage: "App Router apps.",
  practices: "Deplete client providers at the root.",
  mistakes: "Huge 'use client' layout. Random IDs in SSR HTML.",
  language: "typescript",
  caption: "Hydration cost",
  code: "// Keep providers under a client leaf, not the root layout\n",
  figures: [
    {
      src: "/diagrams/performance/perf-hydration.svg",
      alt: "Hydration cost",
      caption: "Hydration cost",
    },
  ],
  examples: [
    {
      id: "mismatch",
      title: "Mismatch",
      about: "Dates/locale.",
      language: "typescript",
      code: "// render timezone-stable strings on server\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-measure",
  title: "Measurement and RUM",
  order: 12,
  summary: "Profilers, field data, and how you prove a win.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Lab: Lighthouse, DevTools, React Profiler. Field: web-vitals + your analytics (RUM). Prove wins with before/after on the same pages and segments (mobile, country). Synthetic monitoring for regressions.",
  beats: ["Field over lab for user truth.", "Segment mobile.", "Budgets in CI for lab."],
  intro: "Seniors must measure, not vibe.",
  why: "You cannot optimize a percentile you don't collect.",
  concept: "CrUX vs first-party RUM.",
  how: "Send CWV with route name and device class.",
  usage: "Product analytics + perf.",
  practices: "Dashboards per route. Alert on p75 regressions.",
  mistakes: "Optimizing localhost. Averaging desktop-only.",
  language: "typescript",
  caption: "Measurement and RUM",
  code: "onINP((m) => post(\"/rum\", { name: \"INP\", value: m.value, route }));\n",
  figures: [
    {
      src: "/diagrams/performance/perf-measure.svg",
      alt: "Measurement and RUM",
      caption: "Measurement and RUM",
    },
  ],
  examples: [
    {
      id: "lab",
      title: "Lab",
      about: "Throttle CPU 4× and Fast 3G.",
      language: "typescript",
      code: "// DevTools Performance → CPU 4×\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-budgets",
  title: "Performance budgets",
  order: 13,
  summary: "Fail CI when a route exceeds bytes or LCP.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "A budget is a number you will not exceed: JS KB per route, LCP < X in CI lab, image weight. Enforce in CI so perf doesn't regress silently. Budgets are product decisions, not engineer taste.",
  beats: ["Pick 2–3 numbers.", "Fail the build.", "Revisit quarterly."],
  intro: "How you keep wins.",
  why: "Regression is the default.",
  concept: "Lighthouse CI, size-limit, bundlesize.",
  how: "lhci assert. bundlesize on the Next client report.",
  usage: "Design systems, marketing.",
  practices: "Different budgets for /editor vs /about.",
  mistakes: "A budget nobody looks at. Blocking deploys on flaky lab LCP only.",
  language: "javascript",
  caption: "Performance budgets",
  code: "module.exports = [{ path: \".next/static/chunks/*.js\", maxSize: \"180 kB\" }];\n",
  figures: [
    {
      src: "/diagrams/performance/perf-budgets.svg",
      alt: "Performance budgets",
      caption: "Performance budgets",
    },
  ],
  examples: [
    {
      id: "lhci",
      title: "Lighthouse CI",
      about: "pwa/perf categories.",
      language: "typescript",
      code: "assert: { assertions: { \"largest-contentful-paint\": [\"error\", { maxNumericValue: 2500 }] } }\n",
    }
  ],
}),

performanceTopic({
  slug: "perf-third-party",
  title: "Third-party scripts",
  order: 14,
  summary: "Tag managers, chat widgets, and INP.",
  prerequisites: [],
  related: ["sec-privacy"],
  isHighYield: false,
  oneLiner: "Third parties steal main thread and privacy. Load them after interaction or idle, sandbox where possible, use Partytown/worker only with eyes open, and prefer server-side tagging. Measure INP before/after a tag.",
  beats: ["Each tag has a cost.", "Consent before marketing tags.", "Self-host if you must."],
  intro: "Real-world perf is tags.",
  why: "Marketing vs engineering conflict.",
  concept: "Script async/defer; fetchpriority.",
  how: "next/script with afterInteractive or lazyOnload.",
  usage: "Analytics, A/B, chat.",
  practices: "One GTM container with ruthless audit.",
  mistakes: "Six pixels in head. Document.write tags.",
  language: "typescript",
  caption: "Third-party scripts",
  code: "import Script from \"next/script\";\n<Script src=\"https://example.com/x.js\" strategy=\"lazyOnload\" />\n",
  figures: [
    {
      src: "/diagrams/performance/perf-third-party.svg",
      alt: "Third-party scripts",
      caption: "Third-party scripts",
    },
  ],
  examples: [
    {
      id: "consent",
      title: "Consent",
      about: "Don't load until granted.",
      language: "typescript",
      code: "if (consent.marketing) loadPixel();\n",
    }
  ],
}),
];
