import type { Topic } from "../../types";
import { testingTopic } from "./factory";

export const testingCurriculumTopics: Topic[] = [
testingTopic({
  slug: "test-pyramid",
  title: "The testing pyramid",
  order: 1,
  summary: "Cheap tests at the base; few E2E at the top.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "A healthy suite has many fast unit tests, fewer component tests that use the real UI, and a handful of E2E journeys. Invert it (mostly E2E) and you get slow, flaky CI. The 'trophy' variant emphasizes component tests for UI apps—same idea: don't make the network the default.",
  beats: ["Cost × reliability.", "E2E for critical paths only.", "Delete tests that don't fail on real bugs."],
  intro: "First question in testing interviews.",
  why: "CI minutes and trust.",
  concept: "Layers: unit → component → integration → e2e.",
  how: "Pick the lowest layer that would catch the bug.",
  usage: "Frontend SPA/RSC apps.",
  practices: "Keep E2E < ~10–20 for a mid app unless you have a platform team.",
  mistakes: "Clicking through every page in Playwright as unit tests.",
  language: "typescript",
  caption: "The testing pyramid",
  code: "const pyramid = { unit: 70, component: 20, e2e: 10 };\n",
  figures: [
    {
      src: "/diagrams/testing/test-pyramid.svg",
      alt: "The testing pyramid",
      caption: "The testing pyramid",
    },
  ],
  examples: [
    {
      id: "trophy",
      title: "Trophy",
      about: "UI apps lean on component tests.",
      language: "typescript",
      code: "// RTL + MSW is the middle bulge\n",
    }
  ],
}),

testingTopic({
  slug: "test-unit",
  title: "Unit testing",
  order: 2,
  summary: "Pure functions and domain rules without the DOM.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "Unit tests pin deterministic logic: pricing, parsers, reducers, URL builders. They should not render 40 components or hit the network. If you need a lot of mocks, it is not a unit—it is an unloved module.",
  beats: ["No I/O.", "Name the rule, not the method.", "Fast enough to run on save."],
  intro: "Still the backbone for domain.",
  why: "Fast feedback on business rules.",
  concept: "Arrange-Act-Assert. Table-driven cases.",
  how: "vitest/jest on a pure function.",
  usage: "Money, dates, permissions.",
  practices: "Property tests for parsers when worth it.",
  mistakes: "Testing private functions via export hacks.",
  language: "typescript",
  caption: "Unit testing",
  code: "import { describe, expect, it } from \"vitest\";\nit(\"applies tax\", () => {\n  expect(tax(1000, 0.2)).toBe(200);\n});\n",
  figures: [
    {
      src: "/diagrams/testing/test-unit.svg",
      alt: "Unit testing",
      caption: "Unit testing",
    },
  ],
  examples: [
    {
      id: "table",
      title: "Table-driven",
      about: "Many cases, one assertion shape.",
      language: "typescript",
      code: "it.each([\n  [0, 0],\n  [100, 20],\n])(\"tax(%i)\", (cents, out) => expect(tax(cents, 0.2)).toBe(out));\n",
    }
  ],
}),

testingTopic({
  slug: "test-component",
  title: "Component testing",
  order: 3,
  summary: "Render, query like a user, assert the UI.",
  prerequisites: [],
  related: ["test-rtl"],
  isHighYield: true,
  oneLiner: "Component tests render a piece of UI, find elements by role/label/text, fire events, and assert the outcome. They catch wiring bugs unit tests miss. Avoid testing implementation (state, class names) unless it is the contract.",
  beats: ["Queries: role, label, text.", "userEvent over fireEvent.", "Assert outcomes, not internals."],
  intro: "The default for React interviews.",
  why: "Refactors should not break tests if behavior holds.",
  concept: "Testing Library philosophy: user-centric queries.",
  how: "render + userEvent.click + expect(screen.getByRole...)",
  usage: "Forms, lists, error states.",
  practices: "Wrap with the same providers the app uses (trimmed).",
  mistakes: "getByTestId for everything. Snapshot of 200-line markup.",
  language: "typescript",
  caption: "Component testing",
  code: "render(<Login />);\nawait user.click(screen.getByRole(\"button\", { name: \"Sign in\" }));\nexpect(await screen.findByText(\"Invalid\")).toBeInTheDocument();\n",
  figures: [
    {
      src: "/diagrams/testing/test-component.svg",
      alt: "Component testing",
      caption: "Component testing",
    },
  ],
  examples: [
    {
      id: "async",
      title: "findBy",
      about: "Wait for async UI.",
      language: "typescript",
      code: "expect(await screen.findByRole(\"alert\")).toHaveTextContent(\"Saved\");\n",
    }
  ],
}),

testingTopic({
  slug: "test-rtl",
  title: "Testing Library queries",
  order: 4,
  summary: "Priority of queries and accessibility coupling.",
  prerequisites: ["test-component"],
  related: [],
  isHighYield: true,
  oneLiner: "Prefer getByRole, getByLabelText, getByPlaceholderText, getByText; testid is last. This couples tests to a11y. If you cannot find a button by name, users cannot either.",
  beats: ["Role + name first.", "queryBy for absence.", "findBy for async."],
  intro: "Interviewers watch your queries.",
  why: "Bad queries freeze bad a11y.",
  concept: "ARIA maps to roles. Labels map to inputs.",
  how: "Use the Testing Playground mental model.",
  usage: "Any RTL test.",
  practices: "eslint-plugin-testing-library.",
  mistakes: "container.querySelector. Matching CSS modules.",
  language: "typescript",
  caption: "Testing Library queries",
  code: "screen.getByRole(\"textbox\", { name: \"Email\" });\n",
  figures: [
    {
      src: "/diagrams/testing/test-rtl.svg",
      alt: "Testing Library queries",
      caption: "Testing Library queries",
    },
  ],
  examples: [
    {
      id: "none",
      title: "queryBy",
      about: "Assert not in the document.",
      language: "typescript",
      code: "expect(screen.queryByRole(\"alert\")).toBeNull();\n",
    }
  ],
}),

testingTopic({
  slug: "test-vitest",
  title: "Vitest (and Jest)",
  order: 5,
  summary: "Runner, mocking, and Vite-native speed.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Vitest is the Vite-era runner: ESM, fast watch, jest-compatible expect/vi. Mock with vi.mock (hoisted) and vi.fn. Prefer injecting seams over mocking every import. jsdom or happy-dom for component tests; node environment for pure units.",
  beats: ["vi.mock is hoisted.", "Don't mock what you don't own if a fake is easier.", "Keep setupFiles small."],
  intro: "Modern FE default in 2026 interviews.",
  why: "Jest knowledge transfers; ESM is the catch.",
  concept: "Worker threads, snapshots optional.",
  how: "vitest.config.ts aligned with Vite aliases.",
  usage: "Unit + component.",
  practices: "Isolate mocks per test. restoreAllMocks.",
  mistakes: "Global mocks that leak. Spying on Date without fake timers care.",
  language: "typescript",
  caption: "Vitest (and Jest)",
  code: "import { vi } from \"vitest\";\nvi.mock(\"./analytics\", () => ({ track: vi.fn() }));\n",
  figures: [
    {
      src: "/diagrams/testing/test-vitest.svg",
      alt: "Vitest (and Jest)",
      caption: "Vitest (and Jest)",
    },
  ],
  examples: [
    {
      id: "time",
      title: "Fake timers",
      about: "Debounce tests.",
      language: "typescript",
      code: "vi.useFakeTimers();\nvi.advanceTimersByTime(300);\n",
    }
  ],
}),

testingTopic({
  slug: "test-msw",
  title: "API mocking with MSW",
  order: 6,
  summary: "Network as a seam: intercept fetch/XHR.",
  prerequisites: [],
  related: ["test-component"],
  isHighYield: true,
  oneLiner: "MSW intercepts requests at the network layer so component tests use real fetch code. Handlers describe the contract. You test loading/error/success without standing a backend. Keep handlers close to the API contract, not to one test's convenience—unless overridden per test.",
  beats: ["Fake the network, not fetch internals.", "Override per test for errors.", "Share handlers with Storybook if useful."],
  intro: "The standard answer vs mocking axios.",
  why: "Catches URL and header mistakes.",
  concept: "Service worker in browser; node interceptors in tests.",
  how: "setupServer(...handlers); server.use() in a test.",
  usage: "Any UI that calls APIs.",
  practices: "One source of truth for fixtures.",
  mistakes: "Mocking fetch globally with a giant if (url.includes).",
  language: "typescript",
  caption: "API mocking with MSW",
  code: "http.get(\"/api/me\", () => HttpResponse.json({ id: \"1\" }));\n",
  figures: [
    {
      src: "/diagrams/testing/test-msw.svg",
      alt: "API mocking with MSW",
      caption: "API mocking with MSW",
    },
  ],
  examples: [
    {
      id: "err",
      title: "500 path",
      about: "Override handler.",
      language: "typescript",
      code: "server.use(http.get(\"/api/me\", () => new HttpResponse(null, { status: 500 })));\n",
    }
  ],
}),

testingTopic({
  slug: "test-e2e",
  title: "E2E testing",
  order: 7,
  summary: "Critical user journeys in a real browser.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "E2E tests run the compiled app against a real (or staging) backend or a seeded preview. Cover sign-in, the money path, and one admin path. They are slow and flake-prone—so few, stable, and isolated with test users.",
  beats: ["Journeys not pages.", "Seed data, don't click-setup forever.", "Trace on failure."],
  intro: "You will be asked what you E2E.",
  why: "Only E2E sees webpack + env + cookies together.",
  concept: "Browser automation + app server.",
  how: "Playwright test.step around a journey.",
  usage: "Checkout, SSO, file upload.",
  practices: "Retry only network flakes you understand. Quarantine is a smell.",
  mistakes: "E2E for every form field. Sharing one user across parallel tests.",
  language: "typescript",
  caption: "E2E testing",
  code: "test(\"checkout\", async ({ page }) => {\n  await page.goto(\"/cart\");\n  await page.getByRole(\"button\", { name: \"Pay\" }).click();\n  await expect(page.getByText(\"Thanks\")).toBeVisible();\n});\n",
  figures: [
    {
      src: "/diagrams/testing/test-e2e.svg",
      alt: "E2E testing",
      caption: "E2E testing",
    },
  ],
  examples: [
    {
      id: "seed",
      title: "API seed",
      about: "Create order via API, then UI pays.",
      language: "typescript",
      code: "await api.createCart(testUser);\n",
    }
  ],
}),

testingTopic({
  slug: "test-playwright",
  title: "Playwright vs Cypress",
  order: 8,
  summary: "Choosing a runner and isolation model.",
  prerequisites: ["test-e2e"],
  related: [],
  isHighYield: false,
  oneLiner: "Playwright: multi-browser, isolated contexts, trace viewer, API testing, good parallel. Cypress: great DX historically, same-origin quirks, different isolation. In 2026 interviews, Playwright is the default answer unless the company is Cypress-deep. Both beat Selenium for FE teams.",
  beats: ["Isolation: Playwright contexts vs Cypress cookies.", "Traces over screenshots-only.", "Don't mix two E2E stacks."],
  intro: "Tool choice question.",
  why: "Wrong tool locks the team.",
  concept: "Browser contexts = parallel users.",
  how: "storageState for auth. test.slow for known heavy.",
  usage: "CI grids.",
  practices: "Auth via API + storageState, not UI login every test.",
  mistakes: "Sleep(5000). Checking pixel positions.",
  language: "typescript",
  caption: "Playwright vs Cypress",
  code: "await page.request.post(\"/api/login\", { data: { email, password } });\n",
  figures: [
    {
      src: "/diagrams/testing/test-playwright.svg",
      alt: "Playwright vs Cypress",
      caption: "Playwright vs Cypress",
    },
  ],
  examples: [
    {
      id: "trace",
      title: "Trace on retry",
      about: "CI artifact.",
      language: "typescript",
      code: "use: { trace: \"on-first-retry\" }\n",
    }
  ],
}),

testingTopic({
  slug: "test-flaky",
  title: "Flaky tests",
  order: 9,
  summary: "Find, quarantine briefly, then delete or fix.",
  prerequisites: [],
  related: [],
  isHighYield: true,
  oneLiner: "A flake is a test that fails without a product change. Causes: time, animation, leaked state, shared users, network, order dependence. Policy: no merge with known flakes; fix the wait (assertions that retry) not a random sleep.",
  beats: ["Flakes train people to ignore CI.", "Prefer web-first assertions.", "Fix the app if the UI is racy."],
  intro: "Senior testing interview.",
  why: "Trust is the asset.",
  concept: "Determinism: fake time, seed, isolation.",
  how: "Playwright toBeVisible retries. RTL findBy.",
  usage: "CI dashboards.",
  practices: "Record flake rate. Kill tests older than a sprint still flaky.",
  mistakes: "retry: 3 as a strategy. Sharing DB rows.",
  language: "typescript",
  caption: "Flaky tests",
  code: "await expect(page.getByRole(\"alert\")).toBeVisible();\n",
  figures: [
    {
      src: "/diagrams/testing/test-flaky.svg",
      alt: "Flaky tests",
      caption: "Flaky tests",
    },
  ],
  examples: [
    {
      id: "time",
      title: "Time",
      about: "Don't assert exact clocks.",
      language: "typescript",
      code: "// assert relative ('2 minutes ago') or mock clock\n",
    }
  ],
}),

testingTopic({
  slug: "test-coverage",
  title: "Coverage",
  order: 10,
  summary: "A flashlight, not a gate of 100%.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Coverage shows untested lines, not correctness. Use it to find risk (auth, money) with 0% tests. 100% often means asserting nothing important. Branch coverage beats line coverage for UI conditionals.",
  beats: ["Risk-weighted.", "Uncovered catch blocks matter.", "Don't chase 100%."],
  intro: "Managers love numbers; engineers must interpret.",
  why: "False confidence is dangerous.",
  concept: "Istanbul/v8 coverage in vitest.",
  how: "Report on changed lines in CI (patch coverage).",
  usage: "Gate on new untested auth files.",
  practices: "Exclude generated code. Don't exclude src/ because it's hard.",
  mistakes: "Writing tests that only execute lines.",
  language: "typescript",
  caption: "Coverage",
  code: "// vitest coverage.include src\n",
  figures: [
    {
      src: "/diagrams/testing/test-coverage.svg",
      alt: "Coverage",
      caption: "Coverage",
    },
  ],
  examples: [
    {
      id: "patch",
      title: "Patch coverage",
      about: "New code must be touched by tests.",
      language: "typescript",
      code: "// CI: fail if changed lines < threshold\n",
    }
  ],
}),

testingTopic({
  slug: "test-snapshots",
  title: "Snapshot testing",
  order: 11,
  summary: "Narrow snapshots; huge ones are lockfiles of noise.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Snapshots are useful for serializers and small pure output (markdown, class lists). Full DOM snapshots break on every CSS tweak and get rubber-stamped. Prefer explicit assertions. Inline snapshots for tiny strings.",
  beats: ["Small, human-reviewed diffs.", "No 500-line snapshots.", "Update consciously."],
  intro: "You will be asked when snapshots are OK.",
  why: "Rubber-stamping hides regressions.",
  concept: "Serializer + git diff as the test.",
  how: "expect(print(ast)).toMatchInlineSnapshot()",
  usage: "Compilers, formatters, icon SVGs.",
  practices: "Review snapshot PRs like code.",
  mistakes: "Snapshot of a whole page per test.",
  language: "typescript",
  caption: "Snapshot testing",
  code: "expect(serialize(node)).toMatchInlineSnapshot(`\"Heading\"`);\n",
  figures: [
    {
      src: "/diagrams/testing/test-snapshots.svg",
      alt: "Snapshot testing",
      caption: "Snapshot testing",
    },
  ],
  examples: [
    {
      id: "css",
      title: "Avoid CSS snapshots",
      about: "Use visual tests instead.",
      language: "typescript",
      code: "// see test-visual\n",
    }
  ],
}),

testingTopic({
  slug: "test-a11y",
  title: "Accessibility testing",
  order: 12,
  summary: "axe in CI plus keyboard reality.",
  prerequisites: [],
  related: ["bp-a11y"],
  isHighYield: false,
  oneLiner: "Automated axe/vitest-axe catches missing names and contrast some of the time. It will not catch keyboard traps or wrong labels that still have a name. Pair with a keyboard pass and one screen-reader pass on the money path.",
  beats: ["axe is necessary not sufficient.", "Assert roles in RTL.", "Don't disable rules to go green."],
  intro: "A11y interviews often include tooling.",
  why: "Law and users.",
  concept: "Static rules + runtime checks.",
  how: "expect(await axe(container)).toHaveNoViolations().",
  usage: "CI on PRs, Storybook addon.",
  practices: "Fail on serious; ticket minor.",
  mistakes: "eslint-disable a11y for 'later'.",
  language: "typescript",
  caption: "Accessibility testing",
  code: "expect(await axe(document.body)).toHaveNoViolations();\n",
  figures: [
    {
      src: "/diagrams/testing/test-a11y.svg",
      alt: "Accessibility testing",
      caption: "Accessibility testing",
    },
  ],
  examples: [
    {
      id: "kbd",
      title: "Keyboard",
      about: "Tab to pay.",
      language: "typescript",
      code: "await user.tab();\nexpect(pay).toHaveFocus();\n",
    }
  ],
}),

testingTopic({
  slug: "test-visual",
  title: "Visual regression",
  order: 13,
  summary: "Pixel diffs for design systems, not every page.",
  prerequisites: [],
  related: [],
  isHighYield: false,
  oneLiner: "Visual tests screenshot a component or page and diff against a baseline. They shine on design systems and marketing. They fail on font/antialias/host differences—so run in Docker/CI with a pinned browser. Don't visual-test every dashboard state.",
  beats: ["Pin the environment.", "Review diffs like snapshots.", "Mask dynamic data."],
  intro: "Tooling interview (Chromatic, Playwright screenshots, Percy).",
  why: "CSS regressions slip past RTL.",
  concept: "Stable viewport + fonts.",
  how: "toHaveScreenshot with masks for dates.",
  usage: "Button matrix, landing page.",
  practices: "One OS in CI. Update baselines deliberately.",
  mistakes: "Visual E2E of a live clock. Different machine baselines.",
  language: "typescript",
  caption: "Visual regression",
  code: "await expect(page.getByTestId(\"card\")).toHaveScreenshot();\n",
  figures: [
    {
      src: "/diagrams/testing/test-visual.svg",
      alt: "Visual regression",
      caption: "Visual regression",
    },
  ],
  examples: [
    {
      id: "mask",
      title: "Mask time",
      about: "Avoid false diffs.",
      language: "typescript",
      code: "mask: [page.getByText(/\\d{1,2}:\\d{2}/)]\n",
    }
  ],
}),

testingTopic({
  slug: "test-contracts",
  title: "Contract testing",
  order: 14,
  summary: "Consumer-driven contracts for APIs you share.",
  prerequisites: [],
  related: ["bp-contracts"],
  isHighYield: false,
  oneLiner: "When frontend and backend ship separately, contract tests (Pact, OpenAPI diff, MSW vs spec) catch breaking JSON changes before integration. The consumer publishes expected requests/responses; the provider verifies them in CI.",
  beats: ["Schema first or Pact.", "Breaking change = version.", "Don't replace E2E entirely."],
  intro: "Senior/platform interviews.",
  why: "Mobile + web + BFF drift.",
  concept: "Provider verification in backend CI.",
  how: "Generate types from OpenAPI; fail on incompatible diffs.",
  usage: "Public APIs, microfrontends.",
  practices: "Version /v2 rather than silent field reuse.",
  mistakes: "Assuming TypeScript types on the server protect the client.",
  language: "typescript",
  caption: "Contract testing",
  code: "openapi-diff ./openapi.yaml ./openapi.prev.yaml\n",
  figures: [
    {
      src: "/diagrams/testing/test-contracts.svg",
      alt: "Contract testing",
      caption: "Contract testing",
    },
  ],
  examples: [
    {
      id: "zod",
      title: "Shared Zod",
      about: "Monorepo shortcut.",
      language: "typescript",
      code: "export const Item = z.object({ id: z.string() });\n",
    }
  ],
}),
];
